# Book settings
title: Cookie Cutter Lab Notebook
author: Chris J. Scientist
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

exclude_patterns: []

execute:
  execute_notebooks: cache
  allow_errors: true
  timeout: 300

parse:
  myst_enable_extensions: 
    - smartquotes
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist

html:
  home_page_in_navbar: false

sphinx:
  config:
    # html_theme: furo
    # html_theme_options:
      # light_css_variables is specific for the furo theme
      # light_css_variables:
        # color-code-background: '#f8f9fb'
